timezone: Australia/Melbourne
name: Kevin Chen
shortname: pjf
description: "Freedom Loving Scientist"
github_repo: https://github.com/KevinChen9117/KevinChen9117.github.io
avatar: pjf_square.jpg
copyright: 2014 Kevin Chen


# Comment out if not wanted, change if wanted.
# twitter: https://twitter.com/
# facebook: https://facebook.com/
# googleplus: https://plus.google.com/+陈海军
github: https://github.com/KevinChen9117
# gittip: https://gittip.com/
# flickr: https://flickr.com/photos/

# February 11th, 2014 campaign.
# See https://thedaywefightback.org for details.
# The 'testing' option will enable the banner, even if it not Feb 11th

thedaywefightback:
    enable: false
    testing: false

# Flattr username
flattr: _pjf

paginate: 5

scholar:
    style: ieee

exclude: 
    - '_assets'
    - 'bin'
    - 'CNAME'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile.rb'
    - 'README.md'

search:
    google:
        cx: 'partner-pub-5040518412301671:2427815553'

# addthis:
#  publisher: ra-52daa5464f2c1c4b

analytics:
  id: UA-47199716-1

disqus:
  shortname: pjf

sidebar:
#  - talks:
#    title: "Talks"
#    url: "/talks"
  - Android_Blog:
    title: "Android技术博客"
    url: "/androidblog"
  - Android:
    title: "Android源码注释"
    url: "/androidcodecomments"
  - Open_Source:
    title: "Android开源库"
    url: "/androidopenlib"
  - Design:
    title: "设计"
    url: "/design
  - Other:
    title: "其他博客"
    url: "/otherblog"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
